/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLAccountConstants.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   account/v1
// Description:
//   Square 1 API

#import "GTLAccountConstants.h"

// Authorization scope
NSString * const kGTLAuthScopeAccountUserinfoEmail = @"https://www.googleapis.com/auth/userinfo.email";
