/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLAccountIremoveUser.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   account/v1
// Description:
//   Square 1 API
// Classes:
//   GTLAccountIremoveUser (0 custom class methods, 0 custom properties)

#import "GTLAccountIremoveUser.h"

// ----------------------------------------------------------------------------
//
//   GTLAccountIremoveUser
//

@implementation GTLAccountIremoveUser
@end
