/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLAccountIcheckUser.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   account/v1
// Description:
//   Square 1 API
// Classes:
//   GTLAccountIcheckUser (0 custom class methods, 1 custom properties)

#import "GTLAccountIcheckUser.h"

// ----------------------------------------------------------------------------
//
//   GTLAccountIcheckUser
//

@implementation GTLAccountIcheckUser
@dynamic ownerid;
@end
