/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLAccountIresetUser.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   account/v1
// Description:
//   Square 1 API
// Classes:
//   GTLAccountIresetUser (0 custom class methods, 1 custom properties)

#import "GTLAccountIresetUser.h"

// ----------------------------------------------------------------------------
//
//   GTLAccountIresetUser
//

@implementation GTLAccountIresetUser
@dynamic ownerid;
@end
