/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLAccountIverifyUser.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   account/v1
// Description:
//   Square 1 API
// Classes:
//   GTLAccountIverifyUser (0 custom class methods, 1 custom properties)

#import "GTLAccountIverifyUser.h"

// ----------------------------------------------------------------------------
//
//   GTLAccountIverifyUser
//

@implementation GTLAccountIverifyUser
@dynamic username;
@end
