/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLAccount.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   account/v1
// Description:
//   Square 1 API

#import "GTLAccountConstants.h"

#import "GTLAccountIcheckUser.h"
#import "GTLAccountIregisterUser.h"
#import "GTLAccountIremoveUser.h"
#import "GTLAccountIresetUser.h"
#import "GTLAccountIverifyUser.h"

#import "GTLQueryAccount.h"
#import "GTLServiceAccount.h"
