/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLAccountIregisterUser.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   account/v1
// Description:
//   Square 1 API
// Classes:
//   GTLAccountIregisterUser (0 custom class methods, 5 custom properties)

#import "GTLAccountIregisterUser.h"

// ----------------------------------------------------------------------------
//
//   GTLAccountIregisterUser
//

@implementation GTLAccountIregisterUser
@dynamic email, fullname, phonenumber, token, vcard;
@end
