/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLAccount_Sources.m
//
// This file can be compiled into projects to avoid adding the individual
// source files for this service.
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   account/v1
// Description:
//   Square 1 API

#import "GTLAccountConstants.m"

#import "GTLAccountIcheckUser.m"
#import "GTLAccountIregisterUser.m"
#import "GTLAccountIremoveUser.m"
#import "GTLAccountIresetUser.m"
#import "GTLAccountIverifyUser.m"

#import "GTLQueryAccount.m"
#import "GTLServiceAccount.m"
