/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLAccountIregisterUser.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   account/v1
// Description:
//   Square 1 API
// Classes:
//   GTLAccountIregisterUser (0 custom class methods, 5 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

// ----------------------------------------------------------------------------
//
//   GTLAccountIregisterUser
//

@interface GTLAccountIregisterUser : GTLObject
@property (nonatomic, copy) NSString *email;
@property (nonatomic, copy) NSString *fullname;
@property (nonatomic, copy) NSString *phonenumber;
@property (nonatomic, copy) NSString *token;
@property (nonatomic, copy) NSString *vcard;
@end
