/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLBlocksConstants.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   blocks/v1
// Description:
//   Square 1 API

#import "GTLBlocksConstants.h"

// Authorization scope
NSString * const kGTLAuthScopeBlocksUserinfoEmail = @"https://www.googleapis.com/auth/userinfo.email";
