/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLBlocks_Sources.m
//
// This file can be compiled into projects to avoid adding the individual
// source files for this service.
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   blocks/v1
// Description:
//   Square 1 API

#import "GTLBlocksConstants.m"

#import "GTLBlocksIblock.m"
#import "GTLBlocksIlist.m"
#import "GTLBlocksIunblock.m"

#import "GTLQueryBlocks.m"
#import "GTLServiceBlocks.m"
