/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLBlocksIlist.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   blocks/v1
// Description:
//   Square 1 API
// Classes:
//   GTLBlocksIlist (0 custom class methods, 0 custom properties)

#import "GTLBlocksIlist.h"

// ----------------------------------------------------------------------------
//
//   GTLBlocksIlist
//

@implementation GTLBlocksIlist
@end
