/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLContactsIqr.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   contacts/v1
// Description:
//   Square 1 API
// Classes:
//   GTLContactsIqr (0 custom class methods, 1 custom properties)

#import "GTLContactsIqr.h"

// ----------------------------------------------------------------------------
//
//   GTLContactsIqr
//

@implementation GTLContactsIqr
@dynamic ownerid;
@end
