/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLContactsIqr.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   contacts/v1
// Description:
//   Square 1 API
// Classes:
//   GTLContactsIqr (0 custom class methods, 1 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

// ----------------------------------------------------------------------------
//
//   GTLContactsIqr
//

@interface GTLContactsIqr : GTLObject
@property (nonatomic, copy) NSString *ownerid;
@end
