/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLContactsIcard.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   contacts/v1
// Description:
//   Square 1 API
// Classes:
//   GTLContactsIcard (0 custom class methods, 1 custom properties)

#import "GTLContactsIcard.h"

// ----------------------------------------------------------------------------
//
//   GTLContactsIcard
//

@implementation GTLContactsIcard
@dynamic ownerid;
@end
