/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLContactsIlist.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   contacts/v1
// Description:
//   Square 1 API
// Classes:
//   GTLContactsIlist (0 custom class methods, 2 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

// ----------------------------------------------------------------------------
//
//   GTLContactsIlist
//

@interface GTLContactsIlist : GTLObject
@property (nonatomic, copy) NSString *ownerid;
@property (nonatomic, retain) NSArray *vcards;  // of NSString
@end
