/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLContactsIlist.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   contacts/v1
// Description:
//   Square 1 API
// Classes:
//   GTLContactsIlist (0 custom class methods, 2 custom properties)

#import "GTLContactsIlist.h"

// ----------------------------------------------------------------------------
//
//   GTLContactsIlist
//

@implementation GTLContactsIlist
@dynamic ownerid, vcards;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map = @{
    @"vcards" : [NSString class]
  };
  return map;
}

@end
