/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLContactsConstants.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   contacts/v1
// Description:
//   Square 1 API

#import "GTLContactsConstants.h"

// Authorization scope
NSString * const kGTLAuthScopeContactsUserinfoEmail = @"https://www.googleapis.com/auth/userinfo.email";
