/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLContacts.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   contacts/v1
// Description:
//   Square 1 API

#import "GTLContactsConstants.h"

#import "GTLContactsIcard.h"
#import "GTLContactsIlist.h"
#import "GTLContactsIqr.h"
#import "GTLContactsIsetUser.h"
#import "GTLContactsIusername.h"

#import "GTLQueryContacts.h"
#import "GTLServiceContacts.h"
