/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLContacts_Sources.m
//
// This file can be compiled into projects to avoid adding the individual
// source files for this service.
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   contacts/v1
// Description:
//   Square 1 API

#import "GTLContactsConstants.m"

#import "GTLContactsIcard.m"
#import "GTLContactsIlist.m"
#import "GTLContactsIqr.m"
#import "GTLContactsIsetUser.m"
#import "GTLContactsIusername.m"

#import "GTLQueryContacts.m"
#import "GTLServiceContacts.m"
