/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLQueryContacts.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   contacts/v1
// Description:
//   Square 1 API
// Classes:
//   GTLQueryContacts (5 custom class methods, 5 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLQuery.h"
#else
  #import "GTLQuery.h"
#endif

@interface GTLQueryContacts : GTLQuery

//
// Parameters valid on all methods.
//

// Selector specifying which fields to include in a partial response.
@property (nonatomic, copy) NSString *fields;

//
// Method-specific parameters; see the comments below for more information.
//
@property (nonatomic, copy) NSString *ownerid;
@property (nonatomic, copy) NSString *token;
@property (nonatomic, copy) NSString *user;
@property (nonatomic, copy) NSString *userid;

#pragma mark - "contacts" methods
// These create a GTLQueryContacts object.

// Method: contacts.contacts.getCard
//  Authorization scope(s):
//   kGTLAuthScopeContactsUserinfoEmail
// Fetches a GTLContactsIcard.
+ (instancetype)queryForContactsGetCardWithOwnerid:(NSString *)ownerid
                                             token:(NSString *)token;

// Method: contacts.contacts.getQr
//  Authorization scope(s):
//   kGTLAuthScopeContactsUserinfoEmail
// Fetches a GTLContactsIqr.
+ (instancetype)queryForContactsGetQrWithOwnerid:(NSString *)ownerid
                                           token:(NSString *)token;

// Method: contacts.contacts.getUsername
//  Authorization scope(s):
//   kGTLAuthScopeContactsUserinfoEmail
// Fetches a GTLContactsIusername.
+ (instancetype)queryForContactsGetUsernameWithOwnerid:(NSString *)ownerid
                                                 token:(NSString *)token;

// Method: contacts.contacts.list
//  Authorization scope(s):
//   kGTLAuthScopeContactsUserinfoEmail
// Fetches a GTLContactsIlist.
+ (instancetype)queryForContactsListWithOwnerid:(NSString *)ownerid
                                          token:(NSString *)token;

// Method: contacts.contacts.setUser
//  Authorization scope(s):
//   kGTLAuthScopeContactsUserinfoEmail
// Fetches a GTLContactsIsetUser.
+ (instancetype)queryForContactsSetUserWithUserid:(NSString *)userid
                                            token:(NSString *)token
                                             user:(NSString *)user;

@end
