/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLQueryAccount.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   account/v1
// Description:
//   Square 1 API
// Classes:
//   GTLQueryAccount (5 custom class methods, 8 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLQuery.h"
#else
  #import "GTLQuery.h"
#endif

@interface GTLQueryAccount : GTLQuery

//
// Parameters valid on all methods.
//

// Selector specifying which fields to include in a partial response.
@property (nonatomic, copy) NSString *fields;

//
// Method-specific parameters; see the comments below for more information.
//
@property (nonatomic, copy) NSString *email;
@property (nonatomic, copy) NSString *fullname;
@property (nonatomic, copy) NSString *ownerid;
@property (nonatomic, copy) NSString *phonenumber;
@property (nonatomic, copy) NSString *token;
@property (nonatomic, copy) NSString *username;
@property (nonatomic, copy) NSString *vcard;

#pragma mark - "account" methods
// These create a GTLQueryAccount object.

// Method: account.account.checkUser
//  Authorization scope(s):
//   kGTLAuthScopeAccountUserinfoEmail
// Fetches a GTLAccountIcheckUser.
+ (instancetype)queryForAccountCheckUserWithUsername:(NSString *)username;

// Method: account.account.registerUser
//  Authorization scope(s):
//   kGTLAuthScopeAccountUserinfoEmail
// Fetches a GTLAccountIregisterUser.
+ (instancetype)queryForAccountRegisterUserWithPhonenumber:(NSString *)phonenumber
                                                     vcard:(NSString *)vcard
                                                  fullname:(NSString *)fullname
                                                     email:(NSString *)email
                                                     token:(NSString *)token;

// Method: account.account.removeUser
//  Authorization scope(s):
//   kGTLAuthScopeAccountUserinfoEmail
// Fetches a GTLAccountIremoveUser.
+ (instancetype)queryForAccountRemoveUserWithOwnerid:(NSString *)ownerid
                                               token:(NSString *)token;

// Method: account.account.resetUser
//  Authorization scope(s):
//   kGTLAuthScopeAccountUserinfoEmail
// Fetches a GTLAccountIresetUser.
+ (instancetype)queryForAccountResetUserWithUsername:(NSString *)username
                                               token:(NSString *)token;

// Method: account.account.verifyUser
//  Authorization scope(s):
//   kGTLAuthScopeAccountUserinfoEmail
// Fetches a GTLAccountIverifyUser.
+ (instancetype)queryForAccountVerifyUserWithUsername:(NSString *)username
                                                token:(NSString *)token;

@end
