/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLQueryAccount.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   account/v1
// Description:
//   Square 1 API
// Classes:
//   GTLQueryAccount (5 custom class methods, 8 custom properties)

#import "GTLQueryAccount.h"

#import "GTLAccountIcheckUser.h"
#import "GTLAccountIregisterUser.h"
#import "GTLAccountIremoveUser.h"
#import "GTLAccountIresetUser.h"
#import "GTLAccountIverifyUser.h"

@implementation GTLQueryAccount

@dynamic email, fields, fullname, ownerid, phonenumber, token, username, vcard;

#pragma mark - "account" methods
// These create a GTLQueryAccount object.

+ (instancetype)queryForAccountCheckUserWithUsername:(NSString *)username {
  NSString *methodName = @"account.account.checkUser";
  GTLQueryAccount *query = [self queryWithMethodName:methodName];
  query.username = username;
  query.expectedObjectClass = [GTLAccountIcheckUser class];
  return query;
}

+ (instancetype)queryForAccountRegisterUserWithPhonenumber:(NSString *)phonenumber
                                                     vcard:(NSString *)vcard
                                                  fullname:(NSString *)fullname
                                                     email:(NSString *)email
                                                     token:(NSString *)token {
  NSString *methodName = @"account.account.registerUser";
  GTLQueryAccount *query = [self queryWithMethodName:methodName];
  query.phonenumber = phonenumber;
  query.vcard = vcard;
  query.fullname = fullname;
  query.email = email;
  query.token = token;
  query.expectedObjectClass = [GTLAccountIregisterUser class];
  return query;
}

+ (instancetype)queryForAccountRemoveUserWithOwnerid:(NSString *)ownerid
                                               token:(NSString *)token {
  NSString *methodName = @"account.account.removeUser";
  GTLQueryAccount *query = [self queryWithMethodName:methodName];
  query.ownerid = ownerid;
  query.token = token;
  query.expectedObjectClass = [GTLAccountIremoveUser class];
  return query;
}

+ (instancetype)queryForAccountResetUserWithUsername:(NSString *)username
                                               token:(NSString *)token {
  NSString *methodName = @"account.account.resetUser";
  GTLQueryAccount *query = [self queryWithMethodName:methodName];
  query.username = username;
  query.token = token;
  query.expectedObjectClass = [GTLAccountIresetUser class];
  return query;
}

+ (instancetype)queryForAccountVerifyUserWithUsername:(NSString *)username
                                                token:(NSString *)token {
  NSString *methodName = @"account.account.verifyUser";
  GTLQueryAccount *query = [self queryWithMethodName:methodName];
  query.username = username;
  query.token = token;
  query.expectedObjectClass = [GTLAccountIverifyUser class];
  return query;
}

@end
