/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLQueryBlocks.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   blocks/v1
// Description:
//   Square 1 API
// Classes:
//   GTLQueryBlocks (3 custom class methods, 4 custom properties)

#import "GTLQueryBlocks.h"

#import "GTLBlocksIblock.h"
#import "GTLBlocksIlist.h"
#import "GTLBlocksIunblock.h"

@implementation GTLQueryBlocks

@dynamic fields, ownerid, targetid, token;

#pragma mark - "blocks" methods
// These create a GTLQueryBlocks object.

+ (instancetype)queryForBlocksBlockWithOwnerid:(NSString *)ownerid
                                      targetid:(NSString *)targetid
                                         token:(NSString *)token {
  NSString *methodName = @"blocks.blocks.block";
  GTLQueryBlocks *query = [self queryWithMethodName:methodName];
  query.ownerid = ownerid;
  query.targetid = targetid;
  query.token = token;
  query.expectedObjectClass = [GTLBlocksIblock class];
  return query;
}

+ (instancetype)queryForBlocksListWithOwnerid:(NSString *)ownerid
                                     targetid:(NSString *)targetid
                                        token:(NSString *)token {
  NSString *methodName = @"blocks.blocks.list";
  GTLQueryBlocks *query = [self queryWithMethodName:methodName];
  query.ownerid = ownerid;
  query.targetid = targetid;
  query.token = token;
  query.expectedObjectClass = [GTLBlocksIlist class];
  return query;
}

+ (instancetype)queryForBlocksUnblockWithOwnerid:(NSString *)ownerid
                                        targetid:(NSString *)targetid
                                           token:(NSString *)token {
  NSString *methodName = @"blocks.blocks.unblock";
  GTLQueryBlocks *query = [self queryWithMethodName:methodName];
  query.ownerid = ownerid;
  query.targetid = targetid;
  query.token = token;
  query.expectedObjectClass = [GTLBlocksIunblock class];
  return query;
}

@end
