/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLQueryReports.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   reports/v1
// Description:
//   Square 1 API
// Classes:
//   GTLQueryReports (1 custom class methods, 5 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLQuery.h"
#else
  #import "GTLQuery.h"
#endif

@interface GTLQueryReports : GTLQuery

//
// Parameters valid on all methods.
//

// Selector specifying which fields to include in a partial response.
@property (nonatomic, copy) NSString *fields;

//
// Method-specific parameters; see the comments below for more information.
//
@property (nonatomic, copy) NSString *date;
@property (nonatomic, copy) NSString *ownerid;
@property (nonatomic, copy) NSString *targetid;
@property (nonatomic, copy) NSString *token;

#pragma mark - "reports" methods
// These create a GTLQueryReports object.

// Method: reports.reports.report
//  Authorization scope(s):
//   kGTLAuthScopeReportsUserinfoEmail
// Fetches a GTLReportsIreport.
+ (instancetype)queryForReportsReportWithOwnerid:(NSString *)ownerid
                                           token:(NSString *)token
                                            date:(NSString *)date
                                        targetid:(NSString *)targetid;

@end
