/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLQueryRequests.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   requests/v1
// Description:
//   Square 1 API
// Classes:
//   GTLQueryRequests (3 custom class methods, 4 custom properties)

#import "GTLQueryRequests.h"

#import "GTLRequestsIacceptUser.h"
#import "GTLRequestsIlist.h"
#import "GTLRequestsIrejectUser.h"

@implementation GTLQueryRequests

@dynamic fields, ownerid, targetid, token;

#pragma mark - "requests" methods
// These create a GTLQueryRequests object.

+ (instancetype)queryForRequestsAcceptUserWithOwnerid:(NSString *)ownerid
                                             targetid:(NSString *)targetid
                                                token:(NSString *)token {
  NSString *methodName = @"requests.requests.acceptUser";
  GTLQueryRequests *query = [self queryWithMethodName:methodName];
  query.ownerid = ownerid;
  query.targetid = targetid;
  query.token = token;
  query.expectedObjectClass = [GTLRequestsIacceptUser class];
  return query;
}

+ (instancetype)queryForRequestsListWithOwnerid:(NSString *)ownerid
                                       targetid:(NSString *)targetid
                                          token:(NSString *)token {
  NSString *methodName = @"requests.requests.list";
  GTLQueryRequests *query = [self queryWithMethodName:methodName];
  query.ownerid = ownerid;
  query.targetid = targetid;
  query.token = token;
  query.expectedObjectClass = [GTLRequestsIlist class];
  return query;
}

+ (instancetype)queryForRequestsRejectUserWithOwnerid:(NSString *)ownerid
                                             targetid:(NSString *)targetid
                                                token:(NSString *)token {
  NSString *methodName = @"requests.requests.rejectUser";
  GTLQueryRequests *query = [self queryWithMethodName:methodName];
  query.ownerid = ownerid;
  query.targetid = targetid;
  query.token = token;
  query.expectedObjectClass = [GTLRequestsIrejectUser class];
  return query;
}

@end
