/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLQueryReports.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   reports/v1
// Description:
//   Square 1 API
// Classes:
//   GTLQueryReports (1 custom class methods, 5 custom properties)

#import "GTLQueryReports.h"

#import "GTLReportsIreport.h"

@implementation GTLQueryReports

@dynamic date, fields, ownerid, targetid, token;

#pragma mark - "reports" methods
// These create a GTLQueryReports object.

+ (instancetype)queryForReportsReportWithOwnerid:(NSString *)ownerid
                                           token:(NSString *)token
                                            date:(NSString *)date
                                        targetid:(NSString *)targetid {
  NSString *methodName = @"reports.reports.report";
  GTLQueryReports *query = [self queryWithMethodName:methodName];
  query.ownerid = ownerid;
  query.token = token;
  query.date = date;
  query.targetid = targetid;
  query.expectedObjectClass = [GTLReportsIreport class];
  return query;
}

@end
