/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLQueryContacts.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   contacts/v1
// Description:
//   Square 1 API
// Classes:
//   GTLQueryContacts (5 custom class methods, 5 custom properties)

#import "GTLQueryContacts.h"

#import "GTLContactsIcard.h"
#import "GTLContactsIlist.h"
#import "GTLContactsIqr.h"
#import "GTLContactsIsetUser.h"
#import "GTLContactsIusername.h"

@implementation GTLQueryContacts

@dynamic fields, ownerid, token, user, userid;

#pragma mark - "contacts" methods
// These create a GTLQueryContacts object.

+ (instancetype)queryForContactsGetCardWithOwnerid:(NSString *)ownerid
                                             token:(NSString *)token {
  NSString *methodName = @"contacts.contacts.getCard";
  GTLQueryContacts *query = [self queryWithMethodName:methodName];
  query.ownerid = ownerid;
  query.token = token;
  query.expectedObjectClass = [GTLContactsIcard class];
  return query;
}

+ (instancetype)queryForContactsGetQrWithOwnerid:(NSString *)ownerid
                                           token:(NSString *)token {
  NSString *methodName = @"contacts.contacts.getQr";
  GTLQueryContacts *query = [self queryWithMethodName:methodName];
  query.ownerid = ownerid;
  query.token = token;
  query.expectedObjectClass = [GTLContactsIqr class];
  return query;
}

+ (instancetype)queryForContactsGetUsernameWithOwnerid:(NSString *)ownerid
                                                 token:(NSString *)token {
  NSString *methodName = @"contacts.contacts.getUsername";
  GTLQueryContacts *query = [self queryWithMethodName:methodName];
  query.ownerid = ownerid;
  query.token = token;
  query.expectedObjectClass = [GTLContactsIusername class];
  return query;
}

+ (instancetype)queryForContactsListWithOwnerid:(NSString *)ownerid
                                          token:(NSString *)token {
  NSString *methodName = @"contacts.contacts.list";
  GTLQueryContacts *query = [self queryWithMethodName:methodName];
  query.ownerid = ownerid;
  query.token = token;
  query.expectedObjectClass = [GTLContactsIlist class];
  return query;
}

+ (instancetype)queryForContactsSetUserWithUserid:(NSString *)userid
                                            token:(NSString *)token
                                             user:(NSString *)user {
  NSString *methodName = @"contacts.contacts.setUser";
  GTLQueryContacts *query = [self queryWithMethodName:methodName];
  query.userid = userid;
  query.token = token;
  query.user = user;
  query.expectedObjectClass = [GTLContactsIsetUser class];
  return query;
}

@end
