/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLRequestsConstants.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   requests/v1
// Description:
//   Square 1 API

#import "GTLRequestsConstants.h"

// Authorization scope
NSString * const kGTLAuthScopeRequestsUserinfoEmail = @"https://www.googleapis.com/auth/userinfo.email";
