/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLReports_Sources.m
//
// This file can be compiled into projects to avoid adding the individual
// source files for this service.
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   reports/v1
// Description:
//   Square 1 API

#import "GTLReportsConstants.m"

#import "GTLReportsIreport.m"

#import "GTLQueryReports.m"
#import "GTLServiceReports.m"
