/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLRequests.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   requests/v1
// Description:
//   Square 1 API

#import "GTLRequestsConstants.h"

#import "GTLRequestsIacceptUser.h"
#import "GTLRequestsIlist.h"
#import "GTLRequestsIrejectUser.h"

#import "GTLQueryRequests.h"
#import "GTLServiceRequests.h"
