/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLReportsIreport.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   reports/v1
// Description:
//   Square 1 API
// Classes:
//   GTLReportsIreport (0 custom class methods, 3 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

// ----------------------------------------------------------------------------
//
//   GTLReportsIreport
//

@interface GTLReportsIreport : GTLObject
@property (nonatomic, copy) NSString *date;
@property (nonatomic, copy) NSString *ownerid;
@property (nonatomic, copy) NSString *targetid;
@end
