/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLReportsIreport.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   reports/v1
// Description:
//   Square 1 API
// Classes:
//   GTLReportsIreport (0 custom class methods, 3 custom properties)

#import "GTLReportsIreport.h"

// ----------------------------------------------------------------------------
//
//   GTLReportsIreport
//

@implementation GTLReportsIreport
@dynamic date, ownerid, targetid;
@end
