/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLRequestsIlist.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   requests/v1
// Description:
//   Square 1 API
// Classes:
//   GTLRequestsIlist (0 custom class methods, 0 custom properties)

#import "GTLRequestsIlist.h"

// ----------------------------------------------------------------------------
//
//   GTLRequestsIlist
//

@implementation GTLRequestsIlist
@end
