/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLReports.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   reports/v1
// Description:
//   Square 1 API

#import "GTLReportsConstants.h"

#import "GTLReportsIreport.h"

#import "GTLQueryReports.h"
#import "GTLServiceReports.h"
