/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLRequestsIacceptUser.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   requests/v1
// Description:
//   Square 1 API
// Classes:
//   GTLRequestsIacceptUser (0 custom class methods, 0 custom properties)

#import "GTLRequestsIacceptUser.h"

// ----------------------------------------------------------------------------
//
//   GTLRequestsIacceptUser
//

@implementation GTLRequestsIacceptUser
@end
