/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLRequests_Sources.m
//
// This file can be compiled into projects to avoid adding the individual
// source files for this service.
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   requests/v1
// Description:
//   Square 1 API

#import "GTLRequestsConstants.m"

#import "GTLRequestsIacceptUser.m"
#import "GTLRequestsIlist.m"
#import "GTLRequestsIrejectUser.m"

#import "GTLQueryRequests.m"
#import "GTLServiceRequests.m"
