/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLRequestsIrejectUser.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   requests/v1
// Description:
//   Square 1 API
// Classes:
//   GTLRequestsIrejectUser (0 custom class methods, 0 custom properties)

#import "GTLRequestsIrejectUser.h"

// ----------------------------------------------------------------------------
//
//   GTLRequestsIrejectUser
//

@implementation GTLRequestsIrejectUser
@end
