/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLServiceBlocks.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   blocks/v1
// Description:
//   Square 1 API
// Classes:
//   GTLServiceBlocks (0 custom class methods, 0 custom properties)

#import "GTLBlocks.h"

@implementation GTLServiceBlocks

#if DEBUG
// Method compiled in debug builds just to check that all the needed support
// classes are present at link time.
+ (NSArray *)checkClasses {
  NSArray *classes = @[
    [GTLQueryBlocks class],
    [GTLBlocksIblock class],
    [GTLBlocksIlist class],
    [GTLBlocksIunblock class]
  ];
  return classes;
}
#endif  // DEBUG

- (instancetype)init {
  self = [super init];
  if (self) {
    // Version from discovery.
    self.apiVersion = @"v1";

    // From discovery.  Where to send JSON-RPC.
    // Turn off prettyPrint for this service to save bandwidth (especially on
    // mobile). The fetcher logging will pretty print.
    self.rpcURL = [NSURL URLWithString:@"/_ah/api/rpc?prettyPrint=false"];
  }
  return self;
}

@end
