# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
# Uncomment this line if you're using Swift
use_frameworks!
workspace '../BackendFramework'

pod 'BackendFramework', :path => '../BackendFramework'

target 'FrameworkTesting' do

end

target 'FrameworkTestingTests' do

end

target 'FrameworkTestingUITests' do

end

